### ISSUE TITLE
Gassetic mssing babel-runtime

### ISSUE THREAD

**Issue by arendjantetteroo** [romanschejbal/gassetic#64] opened 2017-01-11 15:06 UTC
npm install -g gassetic
gassetic@1.0.3 /usr/lib/node_modules/gassetic
├── del@2.2.2 (object-assign@4.1.0, pify@2.3.0, is-path-cwd@1.0.0, rimraf@2.5.4, pinkie-promise@2.0.1, globby@5.0.0, is-path-in-cwd@1.0.0)
├── gulp-tap@0.1.3 (event-stream@3.1.7)
├── glob@7.1.1 (inherits@2.0.3, fs.realpath@1.0.0, path-is-absolute@1.0.1, once@1.4.0, inflight@1.0.6, minimatch@3.0.3)
├── gulp-plumber@1.1.0 (through2@2.0.3)
├── gulp-util@3.0.8 (array-differ@1.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, array-uniq@1.0.3, beeper@1.1.1, dateformat@2.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.3.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.3, multipipe@0.1.2)
├── js-yaml@3.7.0 (esprima@2.7.3, argparse@1.0.9)
├── yargs@6.6.0 (decamelize@1.2.0, get-caller-file@1.0.2, set-blocking@2.0.0, y18n@3.2.1, camelcase@3.0.0, which-module@1.0.0, yargs-parser@4.2.1, require-directory@2.1.1, require-main-filename@1.0.1, cliui@3.2.0, string-width@1.0.2, os-locale@1.4.0, read-pkg-up@1.0.1)
├── gulp@3.9.1 (interpret@1.0.1, pretty-hrtime@1.0.3, deprecated@0.0.1, archy@1.0.0, minimist@1.2.0, v8flags@2.0.11, semver@4.3.6, tildify@1.2.0, chalk@1.1.3, orchestrator@0.3.8, vinyl-fs@0.3.14, liftoff@2.3.0)
├── babel-plugin-transform-runtime@6.15.0 (babel-runtime@6.20.0)
├── babel-cli@6.18.0 (slash@1.0.0, path-is-absolute@1.0.1, fs-readdir-recursive@1.0.0, convert-source-map@1.3.0, v8flags@2.0.11, commander@2.9.0, source-map@0.5.6, glob@5.0.15, output-file-sync@1.1.2, babel-core@6.21.0, chokidar@1.6.1, lodash@4.17.4, babel-register@6.18.0, babel-polyfill@6.20.0, babel-runtime@6.20.0)
├── babel-preset-es2015@6.18.0 (babel-plugin-transform-es2015-spread@6.8.0, babel-plugin-transform-es2015-typeof-symbol@6.18.0, babel-plugin-transform-es2015-arrow-functions@6.8.0, babel-plugin-transform-es2015-block-scoped-functions@6.8.0, babel-plugin-check-es2015-constants@6.8.0, babel-plugin-transform-es2015-literals@6.8.0, babel-plugin-transform-es2015-for-of@6.18.0, babel-plugin-transform-es2015-template-literals@6.8.0, babel-plugin-transform-es2015-destructuring@6.19.0, babel-plugin-transform-es2015-modules-systemjs@6.19.0, babel-plugin-transform-es2015-object-super@6.8.0, babel-plugin-transform-es2015-modules-umd@6.18.0, babel-plugin-transform-es2015-computed-properties@6.8.0, babel-plugin-transform-es2015-modules-amd@6.18.0, babel-plugin-transform-es2015-modules-commonjs@6.18.0, babel-plugin-transform-es2015-shorthand-properties@6.18.0, babel-plugin-transform-es2015-function-name@6.9.0, babel-plugin-transform-es2015-unicode-regex@6.11.0, babel-plugin-transform-es2015-duplicate-keys@6.8.0, babel-plugin-transform-es2015-sticky-regex@6.8.0, babel-plugin-transform-es2015-classes@6.18.0, babel-plugin-transform-es2015-block-scoping@6.21.0, babel-plugin-transform-es2015-parameters@6.21.0, babel-plugin-transform-regenerator@6.21.0)
└── babel-preset-stage-0@6.16.0 (babel-plugin-transform-function-bind@6.8.0, babel-plugin-transform-do-expressions@6.8.0, babel-preset-stage-1@6.16.0)

root@4e1adb116053:/server# gassetic
module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/json/stringify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/gassetic/dist/src/index.js:8:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by arendjantetteroo** [comment] 2017-01-11 15:12
Same issue when installing without the -g flag.

**Comment by romanschejbal** [comment] 2017-01-11 15:20
I couldn't reproduce it, but could you try now? I've just published v1.0.4.

**Comment by arendjantetteroo** [comment] 2017-01-11 15:35
@romanschejbal thanks, that fixes it. 

Get one warning now : 
npm install -g gassetic
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package

Still works, just to let you know.

**Comment by romanschejbal** [comment] 2017-01-11 15:37
Awesome, thanks! Warning should be fixed in newest version 😉

**Closed by romanschejbal** 2017-01-11 15:37 UTC

**Comment by arendjantetteroo** [comment] 2017-01-11 16:10
Thanks! Migrating now, will let you know if something happens.
